export const CustomsSpawnZones =
    [
        "ZoneBrige",
        "ZoneCrossRoad",
        "ZoneDormitory",
        "ZoneGasStation",
        "ZoneFactoryCenter",
        "ZoneFactorySide",
        "ZoneOldAZS",
        "ZoneBlockPost",
        "ZoneTankSquare",
        "ZoneWade",
        "ZoneCustoms",
        "ZoneScavBase"
    ]

export const FactorySpawnZones =
    [
        "BotZone"
    ]
export const InterchangeSpawnZones =
    [
        "ZoneCenterBot", 
        "ZoneIDEA", 
        "ZoneCenter", 
        "ZoneIDEAPark",
        "ZoneTrucks", 
        "ZoneRoad", 
        "ZoneOLI", 
        "ZoneGoshan",
        "ZoneOLIPark", 
        "ZonePowerStation"
    ]
export const LabsSpawnZones =
    [
        "BotZoneBasement", 
        "BotZoneFloor1", 
        "BotZoneFloor2", 
        "BotZoneGate1",
        "BotZoneGate2"
    ]
export const LighthouseSpawnZones =
    [
        "Zone_Containers", 
        "Zone_Rocks", 
        "Zone_Chalet", 
        "Zone_Village",
        "Zone_Bridge", 
        "Zone_OldHouse", 
        "Zone_LongRoad", 
        "Zone_RoofBeach",
        "Zone_DestroyedHouse", 
        "Zone_RoofContainers", 
        "Zone_Blockpost", 
        "Zone_RoofRocks",
        "Zone_TreatmentRocks", 
        "Zone_TreatmentContainers", 
        "Zone_TreatmentBeach", 
        "Zone_Hellicopter",
        "Zone_SniperPeak", 
        "Zone_Island"
    ]
export const ReserveSpawnZones =
    [
        "ZoneRailStrorage", 
        "ZonePTOR1", 
        "ZonePTOR2", 
        "ZoneBarrack",
        "ZoneBunkerStorage", 
        "ZoneSubStorage", 
        "ZoneSubCommand"
    ]
export const GroundZeroSpawnZones =
    [
        "ZoneSandbox"
    ]
export const ShorelineSpawnZones =
    [
        "ZoneGreenHouses", 
        "ZoneIsland", 
        "ZoneForestGasStation", 
        "ZoneGasStation",
        "ZonePowerStation", 
        "ZoneBunker", 
        "ZoneBusStation", 
        "ZonePort",
        "ZoneForestTruck", 
        "ZoneForestSpawn", 
        "ZoneSanatorium1", 
        "ZoneSanatorium2",
        "ZoneStartVillage", 
        "ZoneMeteoStation", 
        "ZoneRailWays", 
        "ZoneSmuglers",
        "ZonePassClose", 
        "ZoneTunnel"
    ]
export const StreetsSpawnZones =
    [
        "ZoneSW01", 
        "ZoneConstruction", 
        "ZoneCarShowroom", 
        "ZoneCinema",
        "ZoneFactory", 
        "ZoneHotel_1", 
        "ZoneHotel_2", 
        "ZoneConcordia_1",
        "ZoneConcordiaParking", 
        "ZoneColumn", 
        "ZoneSW00", 
        "ZoneStilo",
        "ZoneCard1", 
        "ZoneMvd", 
        "ZoneClimova"
    ]
export const WoodsSpawnZones =
    [
        "ZoneWoodCutter", 
        "ZoneHouse", 
        "ZoneBigRocks", 
        "ZoneRoad",
        "ZoneHighRocks", 
        "ZoneMiniHouse", 
        "ZoneRedHouse", 
        "ZoneScavBase2",
        "ZoneClearVill", 
        "ZoneBrokenVill", 
        "ZoneUsecBase", 
        "ZoneStoneBunker",
        "ZoneDepo"
    ]